### ISSUE TITLE
[BUG RUST] - Test commands::ftp::test::test_ftp_upload_ok is failing

### ISSUE THREAD

**Issue by brainrepo** [fourviere/fourviere-podcast#48]
test failing on windows https://github.com/fourviere/fourviere-podcast/actions/runs/6855761586/job/18641504862

**Comment by brainrepo** [comment]
@newfla, I see it failing on Windows. I know that you worked on it. Have you experienced it before?

**Comment by newfla** [comment]
The problem appears to be in the folder used by the test ftp server. `/tmp` is not available in windows. 
I'll prepare a PR asap
